config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'current_user_stats(.:format)' => 'home#current_user_stats'
  post  'attempts(.:format)' => 'attempts#create'
  devise_for :users

end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :attempts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def user_name
  	self.email.split('@').first
  end

  def max_score
  	self.attempts.maximum(:score)
  end

  def attempt_count
  	self.attempts.length
  end

  def mean_score
  	self.attempts.average(:score).to_f.round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController


  # POST /attempts
  # POST /attempts.json
  def create
    @attempt = Attempt.new(attempt_params)
    if user_signed_in?
      @attempt.user_id = current_user.id
    end
    @attempt.save
    respond_to do |format|
      if @attempt.save
        format.js { render action: 'show', status: :created, location: @attempt }
      else
        format.js {}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attempt
      @attempt = Attempt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attempt_params
      params.require(:attempt).permit(:score)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@users = User.all
	end
	
	def show
	end

	def current_user_stats
		if user_signed_in? 
    		@user = current_user
		else
			@user = {:max_score=>'',:mean_score=>'',:attempt_count=>''}
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attempts/_form.html.erb
<%= form_for(@attempt) do |f| %>
  <% if @attempt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attempt.errors.count, "error") %> prohibited this attempt from being saved:</h2>

      <ul>
      <% @attempt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_area :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attempts/edit.html.erb
<h1>Editing Attempt</h1>

<%= render 'form' %>

<%= link_to 'Show', @attempt %> |
<%= link_to 'Back', attempts_path %>

app/views/attempts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attempts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attempts.each do |attempt| %>
      <tr>
        <td><%= attempt.score %></td>
        <td><%= link_to 'Show', attempt %></td>
        <td><%= link_to 'Edit', edit_attempt_path(attempt) %></td>
        <td><%= link_to 'Destroy', attempt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attempt', new_attempt_path %>

app/views/attempts/new.html.erb
<h1>New Attempt</h1>

<%= render 'form' %>

<%= link_to 'Back', attempts_path %>

app/views/attempts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_attempt_path(@attempt) %> |
<%= link_to 'Back', attempts_path %>

app/views/attempts/show.js.erb
$("#globalStatsTable").hide();//append("<%= j render partial: 'home/global_stats_row', locals: {:user=>@current_user } %>");

app/views/home/_current_player_stats.html.erb
<table class="table table-bordered">
	<thead>
        <tr>
          <td><b>My Best Score</b></td>
          <td><b>My Average Score</b></td>
          <td><b>My Attempts</b></td>
        </tr>
	</thead>
	<tbody>
        <tr>
          <td id="bestScore"><%= current_user.max_score %></td>
          <td id="averageScore"><%= current_user.mean_score %></td>
          <td id="attempts"><%= current_user.attempt_count %></td>
        </tr>
	</tbody>
</table>

app/views/home/_global_stats_row.html.erb
		<%= content_tag_for(:tr, user) do %>
			<td class="userName"><%= user.user_name %></td>
			<td class="bestScore"><%= user.max_score %></td>
			<td class="attempts"><%= user.attempt_count %></td>
		<%end%>

app/views/home/index.html.erb
    <div class="container">
      <br>
      <div id="canvasContainer" class="center-block">
            <canvas id = "mainCanvas" width="640" height="440"></canvas>
      </div>
      <script>
        main();
      </script>
      <br>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Stats</h4>
        </div>
          <div class="panel-body">
            <% if user_signed_in? %>
              <%= render "current_player_stats" %>
            <% end %>
            <table id="globalStatsTable" class="table table-bordered">
              <thead>
                <tr>
                  <td><b>Player</b></td>
                  <td><b>Best Score</b></td>
                  <td><b>Attempts</b></td>
                </tr>
              </thead>
              <tbody>
                <% @users.each do |user| %>
                  <%= render "global_stats_row", :user => user %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

app/views/home/show.js.erb
$('#globalStatsTable').append("<%= j render partial: 'global_stats_row', locals: {:user=>@current_user } %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineGameApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
<div class="container">
   <div class="navbar-header">
      <%= link_to "WallTennis", root_path, :class=>"navbar-brand" %>
    </div>
    <div>
		  <% if user_signed_in? %>
		   <ul class="nav navbar-nav">
		   		<li><%= link_to "Signed in as: " + current_user.user_name, edit_user_registration_path %></li>
		   </ul>
		   <ul class="nav navbar-nav navbar-right">
		  	 	<li class="nav navbar-nav pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
		   <ul>
		  <% else %>
		   <ul class="nav navbar-nav">
		  		<li><%= link_to "Sign Up", new_user_registration_path %></li>
		  		<li><%= link_to "Sign In", new_user_session_path %></li>
		  </ul>
		  <% end %>
    </div>
  </div>
 </nav>
  <div id="content">
    <%= yield %>
  </div>
  <div class="footer">
    <div class="container">
      <p class="text-muted text-center"><%=link_to "View Source Code","https://github.com/dbeatrice353/OnlineGameApp" %></p>
    </div>
  </div>
</body>
</html>